version: '3.8'

services:
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=simpod-json-datasource
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  elastic:
    image: elasticsearch:8.13.0
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data

  load_balancer:
    image: nginx:1.25.5-alpine
    container_name: load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./load_balancer/config.conf:/etc/nginx/nginx.conf
    networks:
      grs-net:
        ipv4_address: 172.19.0.3


volumes:
  grafana-storage:
  elastic-storage:

networks:
  grs-net:
    name: grs-net
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
